version: 2.1

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:7a:7b:54:06:8f:e3:1e:1d:80:4b:98:bb:5a:a4:f7"
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
              cd frontend
              npm install
              npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
              cd backend
              npm install
              npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
workflows:
  default:
    jobs:
      - deploy-job
      - build-frontend
      - build-backend